services:
  - type: web
    name: youtube-downloader-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        sync: false
    scaling:
      minInstances: 1
      maxInstances: 1