services:
  - type: web
    name: youtube-downloader-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        sync: false
    rootDir: backend
    scaling:
      minInstances: 1
      maxInstances: 1